dataset_name: aids
path_data: /Users/mariana/Documents/projects/Huawei/tdsurv/data/aids-seqs.pkl
batch_size: 64
learning_rate: .01
log_interval: 10
weight_decay: 1.e-5
num_epochs: 101
horizon: 5
output_file: Results/aids/{}/
landmark: True

lambda_: 0.1
num_steps: 5