dataset_name: single_task
batch_size: 32
learning_rate: .01
log_interval: 1000
weight_decay: 1.e-5
num_epochs: 2
axis: 2
landmark: True
target_lr: .0001

dataset_kwargs:
  horizon: 100
  task_id: 6
  data_path: /Users/mariana/Documents/projects/Huawei/cloudproject/data/Delays/new_data_b03-09_online/

lambda_: 0.1
num_steps: 5