dataset_name: churn_lastfm_months
batch_size: 128
learning_rate: .01
log_interval: 1000
weight_decay: 1.e-4
num_epochs: 100
axis: 2
landmark: True
target_lr: .1
arch:
  type: transformer
  arch_kwargs:
    hidden_size: 16
    seq_len: 226  # Has to be the same as the horizon
    output_dim: 8
    num_layers: 1
    dropout: 0.05

output_file: /Users/mariana/Documents/projects/survival_analysis/survan/Cox/Results/{}/
# output_file: /home/mvargas/code/Huawei/Results/{}/

preprocessed_data: False
calculate_tgt_and_mask: True
dataset_kwargs:
  horizon: 226
  data_path: /Users/mariana/Documents/projects/survival_analysis/data/lastfm-dataset-1K
  # data_path: /home/mvargas/code/Huawei/SurvanData/lastfm-dataset-1K
  use_static_fs: False

lambda_: 0.95
num_steps: 5
verbose: True
stratify: True