dataset_name: aids
axis: 2  # For lambda baseline this has to be 1.
batch_size: 1000
learning_rate: .01
log_interval: 10000
weight_decay: 1.e-4
num_epochs: 200
output_file: Results/aids/{}/
landmark: True
target_lr: .001

dataset_kwargs:
  horizon: 5
  data_path: /Users/mariana/Documents/projects/Huawei/tdsurv/data/aids-seqs.pkl

lambda_: 0.1
num_steps: 5
