dataset_name: placeholder
axis: 2  # For lambda baseline this has to be 1.
batch_size: 128
learning_rate: .1
log_interval: 1000
weight_decay: 1.e-4
num_epochs: 200
output_file: /Users/mariana/Documents/col/lts4/survan/Results/{}/
landmark: True
target_lr: .01
arch:
  type: transformer
  arch_kwargs:
    hidden_size: 16
    seq_len: 20  # Has to be the same as the horizon
    output_dim: 8
    num_layers: 1
    dropout: 0.2

preprocessed_data: False
dataset_kwargs:
  horizon: 11
  dim: 21
  # data_path: /home/mvargas/code/Huawei/Data/aids-seqs.pkl
  data_path: /Users/mariana/Documents/col/lts4/SurvanData/bigrw-seqs.pkl

lambda_: 0.0
num_steps: 5
verbose: False