dataset_name: single_task
batch_size: 128
learning_rate: .01
log_interval: 1000
weight_decay: 1.e-5
num_epochs: 300
axis: 2
landmark: True
target_lr: .1
arch:
  type: transformer
  arch_kwargs:
    hidden_size: 16
    seq_len: 100  # Has to be the same as the horizon
    output_dim: 8
    num_layers: 1
    dropout: 0.05

preprocessed_data: False
output_file: /Users/mariana/Documents/projects/Huawei/Results/{}/
# output_file: /home/mvargas/code/Huawei/Results/{}/
dataset_kwargs:
  horizon: 100
  task_id: 11
  data_path: /Users/mariana/Documents/projects/Huawei/cloudproject/data/Delays/new_data_b03-09_online/
  # data_path: /home/mvargas/code/Huawei/cloudproject/data/Delays/new_data_b03-09_online/splits_1

lambda_: 0.9
num_steps: 5
verbose: True