dataset_name: single_task
batch_size: 64
learning_rate: .01
log_interval: 1000
weight_decay: 1.e-4
num_epochs: 200
axis: 2
landmark: True
target_lr: .001
arch:
  deep: True
  arch_kwargs:
    num_inputs: 39
    num_channels: [64, 32, 16]
    kernel_size: 3
    dilation_factor: 2
    name: tcn_scores

# output_file: /Users/mariana/Documents/projects/Huawei/Results/{}/
output_file: /home/mvargas/code/Huawei/Results/{}/
dataset_kwargs:
  horizon: 100
  # data_path: /Users/mariana/Documents/projects/Huawei/cloudproject/data/Delays/new_data_b03-09_online/
  data_path: /home/mvargas/code/Huawei/cloudproject/data/Delays/new_data_b03-09_online/splits_1

lambda_: 0.0
num_steps: 5