dataset_name: nasa
axis: 2  # For lambda baseline this has to be 1.
batch_size: 32
learning_rate: .01
log_interval: 100
weight_decay: 1.e-4
num_epochs: 20
output_file: /Users/mariana/Documents/projects/survival_analysis/Results/{}/
landmark: False # Check preprocessed_data below.
target_lr: .1
arch:
  type: transformer
  arch_kwargs:
    hidden_size: 16
    seq_len: 363  # Has to be the same as the horizon
    output_dim: 8
    num_layers: 1
    dropout: 0.2

preprocessed_data: False  # In the case of the NASA dataset, this should be True if we want to use landmarking or any lambda value.
# ckpt_path: /Users/mariana/Documents/projects/Huawei/Results/SA/big_rw/transformer/lambda_0.0/landmark_False/seed_{}
dataset_kwargs:
  horizon: 363
  data_path: /Users/mariana/Documents/projects/survival_analysis/SurvanData/NASA.h5

lambda_: .95
num_steps: 5
verbose: True
stratify: True

# For baselines
ddh_hidden_size: 32  # Hidden size for DDH baseline