"""Minimal Dynamic-DeepHit style baseline compatible with Survan datasets.

This script trains a lightweight GRU-based hazard predictor using the existing
utilities in the repository. It relies on the discrete-time targets generated by
``utils.get_targets_and_masks`` and produces survival curves that match the
expected shape used throughout the project.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from functools import partial
from pathlib import Path
import os
import json
from typing import Any, Dict

import haiku as hk
import jax
import jax.numpy as jnp
import numpy as np
import optax
import yaml
import sys
sys.path.append(str(Path('..').resolve()))

from utils import (
    TimesDataGenerator,
    concordance_index,
    get_data,
    train_test_split,
)


@dataclass
class DDHConfig:
    """Configuration for the minimal Dynamic-DeepHit baseline."""

    dataset_name: str
    dataset_kwargs: Dict[str, Any]
    batch_size: int = 64
    learning_rate: float = 1e-3
    num_epochs: int = 50
    hidden_size: int = 128
    test_size: float = 0.2
    axis: int = 2
    seed: int = 0
    log_interval: int = 10
    landmark: bool = False
    ranking_weight: float = 1.0
    ranking_sigma: float = 0.5
    prediction_weight: float = 0.1

    @classmethod
    def from_yaml(cls, path: str | Path) -> "DDHConfig":
        with open(path, "r") as fh:
            raw = yaml.safe_load(fh)

        if "dataset_kwargs" not in raw:
            raise ValueError("Config file must define 'dataset_kwargs'.")

        arch_kwargs = raw.get("arch", {}).get("arch_kwargs", {})
        hidden_size = raw.get("ddh_hidden_size", arch_kwargs.get("hidden_size", cls.hidden_size))
        ranking_weight = raw.get("ddh_ranking_weight", cls.ranking_weight)
        ranking_sigma = raw.get("ddh_ranking_sigma", cls.ranking_sigma)
        prediction_weight = raw.get("ddh_prediction_weight", cls.prediction_weight)

        return cls(
            dataset_name=raw["dataset_name"],
            dataset_kwargs=raw["dataset_kwargs"],
            batch_size=raw.get("batch_size", cls.batch_size),
            learning_rate=raw.get("learning_rate", cls.learning_rate),
            num_epochs=raw.get("num_epochs", cls.num_epochs),
            hidden_size=hidden_size,
            test_size=raw.get("test_size", cls.test_size),
            axis=raw.get("axis", cls.axis),
            seed=raw.get("seed", cls.seed),
            log_interval=raw.get("log_interval", cls.log_interval),
            landmark=raw.get("landmark", cls.landmark),
            ranking_weight=ranking_weight,
            ranking_sigma=ranking_sigma,
            prediction_weight=prediction_weight,
        )


def build_model(hidden_size: int, horizon: int, feature_dim: int) -> hk.Transformed:
    """Create a GRU-based hazard predictor with auxiliary step-ahead head."""

    def forward(inputs: jnp.ndarray) -> tuple[jnp.ndarray, jnp.ndarray]:
        batch_size = inputs.shape[0]
        x = hk.Linear(hidden_size)(inputs)
        x = jax.nn.relu(x)
        x = jnp.swapaxes(x, 0, 1)  # (T, B, hidden)

        core = hk.GRU(hidden_size)
        initial_state = core.initial_state(batch_size)
        outputs, _ = hk.dynamic_unroll(core, x, initial_state)
        outputs = jnp.swapaxes(outputs, 0, 1)  # (B, T, hidden)

        hazard_logits = hk.Linear(horizon)(outputs)
        covariate_preds = hk.Linear(feature_dim)(outputs)
        return hazard_logits, covariate_preds

    return hk.without_apply_rng(hk.transform(forward))


def hazard_loss_from_logits(logits: jnp.ndarray,
                            targets: jnp.ndarray,
                            mask: jnp.ndarray) -> jnp.ndarray:
    bce = optax.sigmoid_binary_cross_entropy(logits, targets)
    weights = mask.astype(jnp.float32)
    normalizer = jnp.maximum(jnp.sum(weights), 1.0)
    return jnp.sum(bce * weights) / normalizer


def _hazard_path_from_logits(logits: jnp.ndarray, axis: int) -> jnp.ndarray:
    hazards = jax.nn.sigmoid(logits)
    if axis == 2:
        return hazards[:, 0, :]
    if axis == 1:
        return hazards
    raise ValueError(f"Unsupported axis value: {axis}")


def _survival_and_cdf_from_logits(logits: jnp.ndarray,
                                  axis: int) -> tuple[jnp.ndarray, jnp.ndarray]:
    hazard_path = _hazard_path_from_logits(logits, axis)

    def step(prev_surv, h_t):
        event_prob = prev_surv * h_t
        new_surv = prev_surv * (1.0 - h_t)
        return new_surv, (new_surv, event_prob)

    init_surv = jnp.ones(hazard_path.shape[0], dtype=hazard_path.dtype)
    _, (surv_seq, event_seq) = jax.lax.scan(step, init_surv, hazard_path.T)

    surv_seq = jnp.concatenate([jnp.ones((1, hazard_path.shape[0])), surv_seq], axis=0)
    surv_curve = surv_seq.T  # (batch, horizon+1)
    cdf = jnp.cumsum(event_seq.T, axis=1)  # (batch, horizon)
    return surv_curve, cdf


def survival_curve_from_logits(logits: jnp.ndarray, axis: int) -> jnp.ndarray:
    surv_curve, _ = _survival_and_cdf_from_logits(logits, axis)
    return surv_curve


def ranking_loss_from_logits(logits: jnp.ndarray,
                             ts: jnp.ndarray,
                             cs: jnp.ndarray,
                             axis: int,
                             sigma: float) -> jnp.ndarray:
    _, cdf = _survival_and_cdf_from_logits(logits, axis)

    ts = jnp.asarray(ts, dtype=jnp.int32)
    cs = jnp.asarray(cs)
    events = (~cs.astype(jnp.bool_)).astype(jnp.float32)

    if cdf.shape[1] == 0:
        return jnp.array(0.0, dtype=jnp.float32)

    ts_clipped = jnp.clip(ts, 1, cdf.shape[1])
    time_indices = ts_clipped - 1

    def gather_for_time(t_idx):
        return cdf[:, t_idx]

    cdf_at_times = jax.vmap(gather_for_time)(time_indices)  # (B, B)
    cdf_i = jnp.take_along_axis(cdf, time_indices[:, None], axis=1).squeeze(axis=1)

    diff = cdf_i[:, None] - cdf_at_times
    rank_matrix = jnp.exp(-diff / sigma)

    time_mask = ts[None, :] > ts[:, None]
    valid = (events[:, None] == 1.0) & time_mask
    valid = valid.astype(jnp.float32)

    denom = jnp.maximum(jnp.sum(valid), 1.0)
    loss = jnp.sum(rank_matrix * valid) / denom
    return loss


def prediction_loss(predictions: jnp.ndarray,
                    inputs: jnp.ndarray) -> jnp.ndarray:
    preds = predictions[:, :-1]
    targets = inputs[:, 1:]
    if preds.shape[1] == 0:
        return jnp.array(0.0, dtype=predictions.dtype)
    diff = preds - targets
    sq = jnp.sum(jnp.square(diff), axis=-1)
    normalizer = preds.shape[1] * preds.shape[2]
    return jnp.sum(sq) / (preds.shape[0] * normalizer)


def median_time_from_survival(surv: jnp.ndarray) -> jnp.ndarray:
    def median_idx(curve: jnp.ndarray) -> jnp.ndarray:
        threshold = 0.5
        crosses = curve <= threshold
        has_cross = jnp.any(crosses)
        idx = jnp.where(has_cross, jnp.argmax(crosses), curve.shape[0] - 1)
        return idx.astype(jnp.float32)

    return jax.vmap(median_idx)(surv)


def brier_score_numpy(h: int,
                      surv: np.ndarray,
                      ts: np.ndarray,
                      cs: np.ndarray) -> float:
    cs = cs.astype(np.bool_)
    h = min(h, surv.shape[1])
    ws = kaplan_meier_numpy(ts - ~cs, ~cs)

    ts_idx = np.clip(ts, 1, surv.shape[1])
    mask_event = np.where((ts <= h) & ~cs, 1, 0)
    comp1 = (1 / ws[ts_idx - 1]) * (0.0 - surv[:, h - 1]) ** 2 * mask_event
    comp1 = np.where(np.isinf(comp1), 0, comp1)
    comp1 = np.where(np.isnan(comp1), 0, comp1)

    mask_cens = np.where((ts > h) | ((ts == h) & cs), 1, 0)
    comp2 = (1 / ws[h - 1]) * (1.0 - surv[:, h - 1]) ** 2 * mask_cens
    comp2 = np.where(np.isinf(comp2), 0, comp2)
    comp2 = np.where(np.isnan(comp2), 0, comp2)

    return float(np.sum(comp1) + np.sum(comp2))


def kaplan_meier_numpy(ts: np.ndarray, cs: np.ndarray) -> np.ndarray:
    cs = cs.astype(np.bool_)
    steps = np.arange(0, np.max(ts) + 1)
    at_risk = np.sum(ts[:, np.newaxis] >= steps, axis=0)
    events = np.sum(ts[~cs, np.newaxis] == steps, axis=0)
    return np.cumprod(1 - events / at_risk)


def integrated_brier_score_numpy(surv: np.ndarray,
                                 ts: np.ndarray,
                                 cs: np.ndarray) -> float:
    t_max = int(np.max(ts))
    if t_max == 0:
        return 0.0
    scorer = partial(brier_score_numpy, surv=surv, ts=ts, cs=cs)
    hs = np.arange(1, t_max + 1)
    scores = np.array([scorer(h) for h in hs])
    return float(np.sum(scores) / (t_max * len(ts)))


def train(config: DDHConfig) -> Dict[str, Any]:
    seqs, ts, cs, target, h_ws, mask = get_data(
        config.dataset_name,
        config.landmark,
        True,
        config.dataset_kwargs,
    )

    seqs = seqs.astype(np.float32)
    target = target.astype(np.float32)
    mask = mask.astype(np.float32)
    h_ws = h_ws.astype(np.float32)

    (X_train, X_test, y_train, y_test, hws_train, hws_test,
     m_train, m_test, ts_train, ts_test, cs_train, cs_test) = train_test_split(
        seqs,
        target,
        h_ws,
        mask,
        ts,
        cs,
        seed=config.seed,
        test_size=config.test_size,
    )

    train_gen = TimesDataGenerator(
        X=X_train,
        ts=ts_train,
        cs=cs_train,
        y=y_train,
        mask=m_train,
        h_ws=hws_train,
        batch_size=config.batch_size,
        rng=np.random.default_rng(config.seed),
    )

    horizon = config.dataset_kwargs.get("horizon", seqs.shape[1])
    feature_dim = seqs.shape[-1]
    model = build_model(config.hidden_size, horizon, feature_dim)

    key = jax.random.PRNGKey(config.seed)
    sample = jnp.asarray(X_train[:1])
    params = model.init(key, sample)

    optimizer = optax.adam(config.learning_rate)
    opt_state = optimizer.init(params)

    def loss_fn(model_params,
                batch_x,
                batch_ts,
                batch_cs,
                batch_y,
                batch_m):
        hazard_logits, cov_preds = model.apply(model_params, batch_x)
        h_loss = hazard_loss_from_logits(hazard_logits, batch_y, batch_m)
        r_loss = ranking_loss_from_logits(hazard_logits,
                                          batch_ts,
                                          batch_cs,
                                          axis=config.axis,
                                          sigma=config.ranking_sigma)
        p_loss = prediction_loss(cov_preds, batch_x)
        total = (h_loss
                 + config.ranking_weight * r_loss
                 + config.prediction_weight * p_loss)
        return total, (h_loss, r_loss, p_loss)

    grad_fn = jax.value_and_grad(loss_fn, has_aux=True)

    hazard_history = []
    ranking_history = []
    prediction_history = []
    total_history = []
    for epoch in range(1, config.num_epochs + 1):
        epoch_total = []
        epoch_hazard = []
        epoch_ranking = []
        epoch_prediction = []
        for batch in train_gen:
            batch_x, batch_ts, batch_cs, batch_y, batch_m, _ = batch
            batch_x = jnp.asarray(batch_x)
            batch_ts = jnp.asarray(batch_ts)
            batch_cs = jnp.asarray(batch_cs)
            batch_y = jnp.asarray(batch_y)
            batch_m = jnp.asarray(batch_m)

            (total_loss, (hazard_loss, ranking_loss, pred_loss)), grads = grad_fn(
                params,
                batch_x,
                batch_ts,
                batch_cs,
                batch_y,
                batch_m,
            )
            updates, opt_state = optimizer.update(grads, opt_state, params)
            params = optax.apply_updates(params, updates)
            epoch_total.append(total_loss)
            epoch_hazard.append(hazard_loss)
            epoch_ranking.append(ranking_loss)
            epoch_prediction.append(pred_loss)

        train_gen.reset()
        mean_total = float(jnp.mean(jnp.stack(epoch_total)))
        mean_hazard = float(jnp.mean(jnp.stack(epoch_hazard)))
        mean_ranking = float(jnp.mean(jnp.stack(epoch_ranking)))
        mean_prediction = float(jnp.mean(jnp.stack(epoch_prediction)))
        total_history.append(mean_total)
        hazard_history.append(mean_hazard)
        ranking_history.append(mean_ranking)
        prediction_history.append(mean_prediction)

        if epoch % config.log_interval == 0 or epoch == 1 or epoch == config.num_epochs:
            print(
                f"Epoch {epoch:03d} | total: {mean_total:.4f} | "
                f"hazard: {mean_hazard:.4f} | ranking: {mean_ranking:.4f} | "
                f"pred: {mean_prediction:.4f}"
            )

    test_x = jnp.asarray(X_test)
    test_y = jnp.asarray(y_test)
    test_m = jnp.asarray(m_test)

    hazard_logits, cov_preds = model.apply(params, test_x)
    test_hazard_loss = float(hazard_loss_from_logits(hazard_logits, test_y, test_m))
    test_ranking_loss = float(
        ranking_loss_from_logits(
            hazard_logits,
            jnp.asarray(ts_test),
            jnp.asarray(cs_test),
            axis=config.axis,
            sigma=config.ranking_sigma,
        )
    )
    test_prediction_loss = float(prediction_loss(cov_preds, test_x))

    surv = survival_curve_from_logits(hazard_logits, axis=config.axis)
    med_times = np.asarray(median_time_from_survival(surv))
    ci = float(concordance_index(med_times, ts_test, cs_test))
    ibs = integrated_brier_score_numpy(
        np.asarray(surv[:, 1:]),
        np.asarray(ts_test),
        np.asarray(cs_test),
    )

    return {
        "params": params,
        "opt_state": opt_state,
        "total_history": total_history,
        "hazard_history": hazard_history,
        "ranking_history": ranking_history,
        "prediction_history": prediction_history,
        "test_hazard_loss": test_hazard_loss,
        "test_ranking_loss": test_ranking_loss,
        "test_prediction_loss": test_prediction_loss,
        "ci": ci,
        "ibs": ibs,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train minimal Dynamic-DeepHit baseline.")
    parser.add_argument("--config", type=str, required=True, help="Path to YAML config file.")
    parser.add_argument("--seed", type=int, default=None, help="Seed for the experiment.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    config = DDHConfig.from_yaml(args.config)
    if args.seed is not None:
        config.seed = args.seed  # overwrite seed in config
        print(f"Seed: {config.seed}")
    
    config.num_epochs = 20

    results = train(config)
    print("Test hazard loss:", f"{results['test_hazard_loss']:.4f}")
    print("Test ranking loss:", f"{results['test_ranking_loss']:.4f}")
    print("Test prediction loss:", f"{results['test_prediction_loss']:.4f}")
    print("Test c-index:", f"{results['ci']:.4f}")
    print("Test IBS:", f"{results['ibs']:.4f}")
    print("Test IBS:", f"{results['ibs']:.4f}")
    path_results = os.path.join('DDH_results', config.dataset_name, f'seed_{config.seed}')
    os.makedirs(path_results, exist_ok=True)
    new_res = {}
    new_res['seed'] = config.seed
    new_res['test_hazard_loss'] = results['test_hazard_loss']
    new_res['test_ranking_loss'] = results['test_ranking_loss']
    new_res['ci'] = results['ci']
    new_res['ibs'] = results['ibs']
    new_res['total_history'] = results['total_history']
    with open(os.path.join(path_results, 'results.json'), 'w') as f:
        json.dump(new_res, f)


if __name__ == "__main__":
    main()
